---
name: Windows

on:
  push:
    branches:
    - main
    - windows-debug-2721
  pull_request:
    branches:
    - main
  schedule:
  # Scheduled workflows run on the latest commit on the default or base branch
  - cron: '0 0 1 * *'
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manually triggering workflow'
        required: true

jobs:
  ci:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Show gfortran Version
      shell: powershell
      run: |
        $env:Path = "C:\\msys64\\mingw64\\bin;" + $env:Path
        gfortran --version
    - name: Where Before and After
      shell: powershell
      run: |
        where cmake
        where gfortran
        $env:Path = "C:\\msys64\\mingw64\\bin;" + $env:Path
        where cmake
        where gfortran
    - name: Where Sanity Check PS
      shell: powershell
      run: |
        where python
        where cmake
        where gfortran
    - name: Where Sanity Check CMD
      shell: cmd
      run: |
        where python
        where cmake
        where gfortran
    - name: Image Version Info
      shell: powershell
      run: |
        Write-Host "IMAGEOS=$env:IMAGEOS||IMAGEVERSION=$env:IMAGEVERSION"
    - name: Create Build Directory
      shell: powershell
      run: |
        New-Item -ItemType Directory -Path .\libbezier-debug\build
    - name: Build and Install libbezier
      shell: powershell
      run: |
        $env:Path = "C:\\msys64\\mingw64\\bin;" + $env:Path
        cmake --version
        cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX:PATH=.\libbezier-debug\usr -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -G MinGW Makefiles -S src\fortran -B .\libbezier-debug\build
        cmake --build .\libbezier-debug\build --config Debug --target install
