---
name: Windows

on:
  push:
    branches:
    - main
    - windows-debug-2721
  pull_request:
    branches:
    - main
  schedule:
  # Scheduled workflows run on the latest commit on the default or base branch
  - cron: '0 0 1 * *'
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manually triggering workflow'
        required: true

jobs:
  ci:
    runs-on: windows-2019
    env:
      NOX_SESSION: '${{ matrix.nox-session }}'
      MINGW_32: 'C:\msys64\mingw32\bin'
      MINGW_64: 'C:\msys64\mingw64\bin'
    strategy:
      matrix:
        nox-session:
        - functional-3.9
    steps:
    - uses: actions/cache@v2
      with:
        path: ~\AppData\Local\pip\Cache
        key: windows-pip
    - uses: actions/checkout@v2
    - name: Update host Python packaging
      shell: cmd
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools wheel "nox >= 2020.12.31"
    - name: Show gfortran version
      shell: powershell
      run: |
        $NOX_SESSION = $env:NOX_SESSION
        If ($NOX_SESSION.EndsWith("-32")) {
          $MINGW = $env:MINGW_32
        } Else {
          $MINGW = $env:MINGW_64
        }
        $env:Path = "$MINGW;" + $env:Path
        gfortran --version
    - name: Warn for Image Version
      # See: https://github.com/actions/virtual-environments/issues/2721
      # The `IMAGEVERSION=20210211.1` version is suspected to be bad.
      shell: powershell
      run: |
        $IMAGEVERSION = $env:IMAGEVERSION
        Write-Host "IMAGEOS=$env:IMAGEOS||IMAGEVERSION=$IMAGEVERSION"
        If ($IMAGEVERSION -eq "20210211.1") {
          Write-Host "Warning: IMAGEVERSION=20210211.1 is expected to fail"
        }
    - name: Invoke nox
      shell: powershell
      run: |
        $NOX_SESSION = $env:NOX_SESSION
        If ($NOX_SESSION.EndsWith("-32")) {
          $MINGW = $env:MINGW_32
        } Else {
          $MINGW = $env:MINGW_64
        }
        $env:Path = "$MINGW;" + $env:Path
        nox --session $env:NOX_SESSION
